# glosario.py

# Claves: insulto en inglés o francés
# Valor: traducción equivalente al español
GLOSARIO = {
    # Inglés
    "faggot": "maricón",
    "nigger": "negrata",
    "nigga": "negrata",
    "twat": "gilipollas",
    "bastard": "cabrón",
    "scum": "escoria",
    "fucking": "puto",
    "cunt": "puta",
    "retard": "retrasado",
    "dyke": "bollera",
    "tranny": "travelo",
    "bitch": "zorra",
    "slut": "zorra",
    "spic": "sudaca",
    "chink": "chino de mierda",
    "kike": "judío de mierda",
    "raghead": "moraco",
    "gook": "asiático de mierda",
    "cripple": "lisiado",
    "fatass": "gordo asqueroso",
    "leftwing filth": "rojo de mierda",
    "third-world trash": "basura del tercer mundo",
    "mud people": "sudacas",
    "moslem scum": "escoria musulmana",
    "dog eaters": "comeperros",
    "cumdumpster": "maricón",
    "whore": "puta",
    "fruitcake": "maricón",
    "roastie": "puta",
    "piece of shit": "trozo de mierda",
    "moron": "subnormal",
    "motherfucker": "hijo de puta",
    "son of a bitch": "hijo de puta",
    # Francés
    "pédé": "maricón",
    "connard": "gilipollas",
    "pute": "puta",
    "salaud": "cabrón",
    "merde": "mierda",
    "enculé": "cabronazo",
    "gros lard": "cerdo gordo",
    "bougnoule": "mora de mierda",
    "bougnoul": "moro de mierda",
    "allumeuse": "calientapollas",
    "niakoué": "chinito",
    "youpin": "judío de mierda",
    "tafiole": "maricón",
    "gouine": "bollera",
    "mongolien": "mongolo",
    "sale noir": "sucio negro",
    "grosse vache": "vaca gorda",
    "racaille": "escoria",
    "tiers-mondiste": "basura tercermundista",
    "beauf": "paleto",
    "travelot": "travelo",
    "tantouze": "marica",
    "tas de merde": "montón de mierda",
    "attardé": "retrasado",
    "enfoiré": "cabronazo",
    "garce": "perra",
    "raton": "panchito",
    "enculé de socialo": "rojo de mierda",
    "enfoiré de fachos": "facha de mierda",
    "enfoiré de gauchos": "rojo de mierda"
}
